#!/usr/bin/env ruby
# frozen_string_literal: true
#
# check_z80_call_convention.rb - which register the compiler actually reads a
# Z80 return value from, measured instead of assumed.
#
# AGENTS.md states that a 16-bit return is in HL.  That is the sdcccall(1) rule.
# The modules in this tree are compiled plain -mz80 while the SDCC library that
# gets linked in is built sdcccall(1), so BOTH conventions exist in the same
# image, and which one a given call uses has to be read off the generated code.
# AGENTS.md says exactly that.  This is the script that makes it true for the
# assembly entry points it cannot see.
#
# WHY IT EXISTS
# -------------
# platform/zeta-v2/tick.s's muzix_tick_now() returned its 16-bit value in HL,
# which is what the AGENTS.md rule says to do.  SDCC's own generated caller did
# `call _muzix_tick_now / ld hl,#600 / add hl,de` - it read DE - so every
# deadline in the system was computed from a register the caller happened to be
# carrying.  The bounded console read therefore timed out almost immediately,
# the shell never reached a prompt, and the machine re-ran kernel_main in a loop
# several hundred times.  It is invisible from both ends: the assembly is
# self-consistent, the C is self-consistent, the host tests all pass (they test
# a C model of the routine, not the Z80 one), and the failure only shows up as a
# machine that will not boot.
#
# So the check is mechanical.  It compiles a probe that calls the function and
# adds a constant to the result - the exact shape of every deadline in the tree -
# and reads which register SDCC consumed.  If the answer changes, or the probe
# stops compiling, this fails.
#
# The probe deliberately uses `+ 600`: an expression SDCC has to materialise
# rather than fold, so the register choice shows up in the output at all.  A bare
# `use(f())` would compile to a call and nothing else and would tell us nothing.
#
# Usage: check_z80_call_convention.rb <repo-root>
#
# What it is not: a general calling-convention checker.  It answers one question
# about the assembly entry points it is given, and it is worth extending to
# those only - a C-to-C call in this tree is already covered by the compiler
# being the compiler.

require "fileutils"

ROOT = ARGV[0] or abort "usage: check_z80_call_convention.rb <repo-root>"

# Each entry: a header to include for the prototype, a C expression that calls
# the function and consumes its 16-bit return, and the register the compiler is
# expected to read the value out of.
# Two shapes, two different rules, and both of them are invisible from the
# assembly side:
#
#   a plain -mz80 function returning 16 bits  -> the value is read from DE
#   a plain -mz80 function returning  8 bits  -> the value is read from A
#
# The 16-bit one is what muzix_tick_now() got wrong.  Both are checked because
# both are load-bearing in the assembly that consumes them - muzix_tick_expired
# returns in A, and muzix_tick_now's callers read DE - and neither is visible
# from either end of the call.
#
# The tree-wide convention, measured on a probe and cross-checked against a real
# call site (kernel_loop.c's muzix_system_entry_current_pid):
#
#     param1        -> HL
#     16-bit return -> DE      <- NOT HL.  AGENTS.md quotes the sdcccall(1) rule.
#     8-bit return  -> A
#
# AGENTS.md's other half is right: platform/zeta-v2/uart_io.h's MUZIX_ZETA_SDCCCALL1
# expands to nothing on this build (the #else branch), so the uart entry points
# are plain calls too, and the `ld hl,#0x0000 / call / ld c,a / ld b,#0x00` that
# comes out is param1 in HL and an 8-bit return in A.
PROBES = [
  {
    header: "platform/zeta-v2/tick.h",
    what: "muzix_tick_now() 16-bit return",
    expr: "muzix_tick_now() + 600",
    expect: :plain_16bit,
  },
  {
    header: "platform/zeta-v2/uart_io.h",
    what: "muzix_zeta_uart_available() 8-bit return",
    expr: "(uint16_t)muzix_zeta_uart_available((void *)0) + 600",
    expect: :plain_8bit,
  },
].freeze

# 16-bit returns from a plain -mz80 function in this tree are in DE.  The
# sdcccall(1) functions (the uart ones) return 8-bit values in A, so the probe
# for those is on the 8-bit rule and DE is not expected there.
EXPECT_16BIT_REG = "e"
EXPECT_8BIT_REG = "a"

errors = []

PROBES.each_with_index do |probe, n|
  name = "z80_callconv_probe_#{n}"
  src = File.join(ROOT, "build", "#{name}.c")
  out = File.join(ROOT, "build", "#{name}.s")

  FileUtils.mkdir_p(File.dirname(src))

  File.write(src, <<~C)
    /* Generated by tools/check_z80_call_convention.rb - not a source file. */
    #include <stdint.h>
    #include "#{probe[:header]}"

    uint16_t z80_callconv_probe_#{n}(void)
    {
        return (uint16_t)(#{probe[:expr]});
    }
  C

  cmd = [ENV.fetch("SDCC", "sdcc"), "-mz80", "--opt-code-size",
         "-I", ROOT, "-I", File.join(ROOT, "lib"),
         "-I", File.join(ROOT, "platform/zeta-v2"),
         "-S", "-o", out, src]
  ok = system(*cmd, out: File::NULL, err: File::NULL)

  unless ok
    errors << "#{probe[:what]}: the probe did not compile. " \
              "That is a failure of this check, not a pass - if the prototype " \
              "moved, the header moved, or the compiler is missing, this " \
              "cannot tell the register any more and the build should stop."
    next
  end

  body = File.read(out)
  # The addition is the only thing in the probe that can consume a register, so
  # the sequence after the call is what says which one the compiler chose.
  after = body[/call\s+(\S+)(.*?)\n\s*ret/m, 2].to_s

  case probe[:expect]
  when :plain_16bit
    reads_de = after =~ /add\s+hl,\s*de\b/ ||
               after =~ /ld\s+[a-z]+,\s*e\b/ ||
               after =~ /ld\s+[a-z]+,\s*d\b/
    unless reads_de
      errors << "#{probe[:what]}: expected the value to be read from DE after " \
                "the call - the plain -mz80 convention this tree compiles " \
                "with - and the generated code does not read DE there.  " \
                "Either the convention changed or the routine returns in the " \
                "wrong register, and if it is the latter then every deadline " \
                "in the system is computed from whatever the caller was " \
                "carrying: the console read times out at once, the shell never " \
                "reaches a prompt, and the machine re-runs kernel_main in a " \
                "loop.  See the note on muzix_tick_now in tick.s."
    end
  when :plain_8bit
    # An 8-bit value is widened to 16, so the compiler takes the low byte from
    # the return register and supplies the high one itself.  That is exactly the
    # `ld c,a / ld b,#0x00` shape, and matching on the zero-extension is what
    # makes this robust: it would still pass if SDCC reordered the loads.
    unless after =~ /ld\s+c,\s*a\b/ && after =~ /ld\s+b,\s+#0x00\b/
      errors << "#{probe[:what]}: expected the 8-bit return to be widened from " \
                "A (the `ld c,a / ld b,#0x00` shape), and the generated code " \
                "does not do that.  muzix_tick_expired() and the uart routines " \
                "all return in A on the strength of that rule; if it changed, " \
                "every deadline test in the system would read a register that " \
                "nobody wrote."
    end
  end

  FileUtils.rm_f(src)
  FileUtils.rm_f(out)
end


# The register the ASSEMBLY leaves the value in is the other half of this, and
# no C probe can see it: SDCC's codegen is byte-for-byte identical whether or
# not the routine honours the convention, because the compiler is not the thing
# that is wrong here.  tools/check_tick_counts.rb boots the ROM and asserts the
# tick counts, and it does not catch this either - measured, not assumed.  With
# the value left in HL the bounded console read gets a deadline built from a
# garbage register and expires instantly, which after the shell was taught to
# retry a timeout is a 100%-CPU spin rather than a crash: the shell still runs,
# top still counts, and the check passes.  The earlier symptom - several hundred
# re-entries of kernel_main - needed the shell to treat the instant timeout as
# end of file, which is a bug that is now fixed, and with that bug fixed the
# register mistake is silent.
#
# So this is the only thing that catches it, and it is a lint: it reads the
# routine's source and requires the register SDCC reads.  It will not survive a
# rewrite that keeps the behaviour and changes the instructions, and that is the
# trade - a behavioural test is what should catch that, and the two together are
# worth more than either alone.
#
# It has already been caught once by that trade going the other way.  The fix
# for the counter's byte order in muzix_tick_now() builds the value in HL and
# leaves it in both registers with `ex de,hl`, which is one byte shorter than
# the `ld d,h / ld e,l` this lint was written to look for, and the lint read the
# rewrite as "never loads d and e" and failed the build.  Two ways of leaving a
# 16-bit value in DE are therefore accepted here, and the behavioural test
# (platform/zeta-v2/test_tick.c, which runs the real tick.s as a linked Z80
# image) is what is supposed to notice if either of them ever stops working.
RETURN_REGISTERS = [
  {
    source: "platform/zeta-v2/tick.s",
    routine: "_muzix_tick_now:",
    must_set: %w[d e],
    note: "a 16-bit plain -mz80 return is read from DE; HL is the sdcccall(1)" \
          "rule and is what this got wrong",
  },
].freeze

RETURN_REGISTERS.each do |r|
  path = File.join(ROOT, r[:source])
  unless File.exist?(path)
    errors << "#{r[:note]}: #{r[:source]} does not exist, so this cannot be checked."
    next
  end
  body = File.read(path)
  # The routine's text, up to the first label at column 0 that is not its own.
  seg = body[/^#{Regexp.escape(r[:routine])}(.*?)(?=^\S)/m, 1]
  if seg.nil?
    errors << "#{r[:note]}: #{r[:routine]} was not found in #{r[:source]}, so " \
              "this cannot be checked.  A lint that cannot find its subject " \
              "must not pass."
    next
  end
  loads_de = r[:must_set].all? { |reg| seg =~ /\bld\s+#{reg},/ }
  # `ex de,hl` leaves the value in DE and in HL, which is what this tree wants
  # from a 16-bit return: DE for a plain -mz80 caller, HL for an sdcccall(1)
  # one.  It is only accepted where the routine's own name says the value is
  # being handed back, not anywhere in the module.
  exchanges = seg =~ /\bex\s+de,\s*hl\b/
  unless loads_de || exchanges
    missing = r[:must_set].reject { |reg| seg =~ /\bld\s+#{reg},/ }
    errors << "#{r[:note]}: #{r[:routine]} never loads #{missing.join(' and ')} " \
              "and never exchanges HL into DE, so it does not leave a " \
              "#{r[:must_set].join(':')} result for the caller.  Every deadline " \
              "in the system is then computed from whatever the caller was " \
              "carrying."
  end
end

unless errors.empty?
  warn "FAIL: the Z80 return-value convention is not what the assembly assumes"
  errors.each { |e| warn "  x #{e}" }
  warn ""
  warn "  A C caller reads a 16-bit return from DE for a plain -mz80 function"
  warn "  in this tree, not HL.  That is measured, not documented: see the"
  warn "  call site of muzix_system_entry_current_pid in kernel_loop, which"
  warn "  compiles to `ld (hl),e / inc hl / ld (hl),d / bit 7,d`."
  exit 1
end

puts "  x Z80 return-value registers match the generated callers: OK"
